---
name: Lint

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-latest

    strategy:
      matrix:
        go: ["1.19", "1.20"]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go }}

      - name: Install linter
        run: go install honnef.co/go/tools/cmd/staticcheck

      - name: Lint
        run: staticcheck ./...
